[tasks.default]
    links = [
        [".tmuxrc"],
        [".gitconfig"],
    ]

[tasks.zsh]
    links = [
        [".zlogin"],
        [".zlogout"],
        [".zpreztorc"],
        [".zprofile"],
        [".zshenv"],
        [".zshrc"],
    ]
    cmds = [
        ["git", "clone", "--recursive",
            "https://github.com/sorin-ionescu/prezto.git",
            "${HM_DEST}/.zprezto"]
    ]

[tasks.vim]
    links = [
        [".vimrc"],
    ]
    cmds = [
        ["curl", "-fLo", "${HM_DEST}/.vim/autoload/plug.vim", "--create-dirs",
            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"],
        ["vim", "-c", "PlugInstall"],
    ]

[tasks.nvim]
    links = [
        [".nvimrc"],
    ]
    cmds = [
        ["curl", "-fLo", "${HM_DEST}/.nvim/autoload/plug.vim", "--create-dirs",
            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"],
        ["nvim", "-c", "PlugInstall"],
    ]

[tasks.server]
    cmds = [
        ["cat", "id_rsa.pub", ">>", "${HM_DEST}/.ssh/authorized_keys"],
        ["chmod", "0600", "${HM_DEST}/.ssh/authorized_keys"],
    ]

